version: '3'
services:
  blogdupe-backend:
    build: .
    restart: always
    ports:
      - "6000:6000"
    environment:
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
