version: '3'
services:
  blogdupe-backend:
    build:
      context: .
      args:
        - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
        - CLOUDINARY_KEY=${CLOUDINARY_KEY}
        - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=production      
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - PORT = ${PORT}
    command: ["./node_modules/.bin/keystone-next", "start"]
